<script>
	// imports
	import mapboxgl, { Popup } from "mapbox-gl";
	import { createEventDispatcher, onMount } from "svelte";

	import {
		mapsource,
		maplayer,
		mapfunctions,
		mapobject,
		mapstyle,
	} from "./mapstore.js";

	//styling
	// import 'mapbox-gl/dist/mapbox-gl-draw.css'
	// import "./css/mapbox-gl.css";

	let webgl_canvas;
	export let width = "100vw";
	export let height = "100vh";


	/// MAP creation
	async function init() {
		console.warn(webgl_canvas);

		$mapobject = new mapboxgl.Map({
			container: "mapcontainer",
			style: mapstyle,
			pitch: 30,
			center: [0, 52],
			zoom: 2,
		});


		$mapobject.addControl(new mapboxgl.NavigationControl(), "bottom-right");


		$mapobject.doubleClickZoom.disable();

		// correct error - ignore 403 missing tiles
		$mapobject.on("error", (e) => {
			if (e.error.status != 403)
				console.error(e.error.status, e.error.message);
		});

		$mapobject.on("load", SetLayers);
	}


	/// Set all Mapbox Parameters ///
	export async function SetLayers() {
		// set mapbox layers
		console.log("set layers");

		mapsource.subscribe(async () => {
			// set the sources
			for (const [key, value] of Object.entries($mapsource)) {
				// console.log(key, value);
				if ($mapobject.getSource(key)) $mapobject.removeSource(key);
				// if (value.hasOwnProperty('data')) value.data = await value.data; // for async loads
				if (!$mapobject.getSource(key))
					$mapobject.addSource(key, value); // as it may nto be removable
			}
		});

		maplayer.subscribe(async () => {
			// set the layers
			for (const value of $maplayer) {
				console.log("layer", value);
				if ($mapobject.getLayer(value.id))
					$mapobject.removeLayer(value.id);
				$mapobject.addLayer(value);
			}
		});
		mapfunctions.subscribe(async () => {
			// console.warn('fnreload',$mapfunctions)
			// set the functions
			for (const e of $mapfunctions) {
				// $mapobject.off(e.event, e.layer, e.callback);
				if (!e.off) console.log("adding", e.event, e.layer);
				$mapobject.on(e.event, e.layer, e.callback);
			}
		});



		// // move mapobject to location
		// $mapobject.fitBounds(location.bounds, {
		// 	padding: 20,
		// });
	}

	export function change_data(layer, data) {
		$mapobject.getSource(layer).setData(data);
	}


	/// main
	onMount(init);
</script>

<!-- Script autogenerated by Svelte-Jinja (author: Dan Ellis) -->
<main>
	<div
		class="mapboxgl-canvas"
		tabindex="0"
		aria-label="Map"
		id="mapcontainer"
		style="width: {width}; height: {height}; "
		bind:this={webgl_canvas}
	/>
</main>

<style lang="scss">
	main {
		position: absolute;
		top: 0;
		left: 0;
		margin: auto;
	}
</style>
